export const columns = [
  {
    field: "id",
    headerName: "ID",
    type: "number",
    width: 50,
    headerAlign: "center",
    align: "center",
    flex: 0.5,
  },
  {
    field: "lastname",
    headerName: "Nom",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "firstname",
    headerName: "Prénom",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "gender",
    headerName: "Sexe",
    width: 90,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "birthdate",
    headerName: "Date de naissance",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "phone",
    headerName: "Numéro de téléphone",
    type: "number",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "mail",
    headerName: "Adresse mail",
    width:200,
    headerAlign: "center",
    align: "center",
    flex:2,
  },
  {
    field: "etat",
    headerName: "Etat",
    width: 110,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "datecreation",
    headerName: "Date de création",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
  {
    field: "trash",
    headerName: "Action",
    width: 150,
    headerAlign: "center",
    align: "center",
    flex: 1,
  },
];

export const rows = [
  {
    id: "1",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "2",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "3",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "4",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "5",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "6",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
  {
    id: "7",
    firstname: "Bassem",
    lastname: "Chouchen",
    gender: "Homme",
    birthdate: "18/01/2001",
    phone: "53340383",
    mail: "bassemchouchou@gmail.com",
    etat: "Actif",
    datecreation: "28/02/2024",
  },
];
